"""Harvest events and sales; no changes to existing cultivation records."""
from alembic import op
from sqlalchemy import text

revision = 'a5d094e0c263'
down_revision = 'f4c083d9b152'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    CREATE TABLE harvest_events (
      harvest_event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      farm_crop_id integer NOT NULL REFERENCES farm_crops ON DELETE RESTRICT,
      farm_id integer NOT NULL REFERENCES farms ON DELETE RESTRICT,
      plot_id integer REFERENCES farm_plots ON DELETE RESTRICT,
      farm_block_id integer REFERENCES farm_blocks ON DELETE RESTRICT,
      harvested_on date NOT NULL,
      quantity numeric(14,4) NOT NULL CHECK(quantity>0 AND quantity<10000000000),
      unit varchar(20) NOT NULL CHECK(unit IN ('kg','g','tonne','quintal','unit','crate','box','bag','bunch')),
      grade varchar(100),
      wastage_quantity numeric(14,4) CHECK(wastage_quantity>=0 AND wastage_quantity<=quantity),
      notes text,
      created_by integer NOT NULL REFERENCES users, updated_by integer NOT NULL REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      request_key uuid NOT NULL, request_payload jsonb NOT NULL,
      UNIQUE(created_by,request_key));
    CREATE INDEX harvest_events_cycle_date_idx ON harvest_events(farm_crop_id,harvested_on DESC,harvest_event_id DESC);
    CREATE INDEX harvest_events_farm_idx ON harvest_events(farm_id);
    CREATE INDEX harvest_events_plot_idx ON harvest_events(plot_id) WHERE plot_id IS NOT NULL;
    CREATE INDEX harvest_events_block_idx ON harvest_events(farm_block_id) WHERE farm_block_id IS NOT NULL;
    CREATE TABLE harvest_sales (
      harvest_sale_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      harvest_event_id integer NOT NULL REFERENCES harvest_events ON DELETE RESTRICT,
      quantity_sold numeric(14,4) NOT NULL CHECK(quantity_sold>0 AND quantity_sold<10000000000),
      unit varchar(20) NOT NULL,
      price_per_unit numeric(14,4) CHECK(price_per_unit>0 AND price_per_unit<10000000000),
      total_amount numeric(14,2) NOT NULL CHECK(total_amount>0 AND total_amount<1000000000000),
      buyer_name varchar(200), sold_on date NOT NULL, notes text,
      created_by integer NOT NULL REFERENCES users, updated_by integer NOT NULL REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      request_key uuid NOT NULL, request_payload jsonb NOT NULL,
      UNIQUE(created_by,request_key),
      CHECK(price_per_unit IS NULL OR total_amount=round(quantity_sold*price_per_unit,2)));
    CREATE INDEX harvest_sales_event_date_idx ON harvest_sales(harvest_event_id,sold_on DESC,harvest_sale_id DESC);

    CREATE FUNCTION harvest_event_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE cycle_row record; sold numeric; first_sale date;
    BEGIN
      SELECT * INTO cycle_row FROM farm_crops WHERE farm_crop_id=NEW.farm_crop_id FOR UPDATE;
      IF NOT FOUND OR ROW(NEW.farm_id,NEW.plot_id,NEW.farm_block_id) IS DISTINCT FROM
         ROW(cycle_row.farm_id,cycle_row.plot_id,cycle_row.farm_block_id) THEN
        RAISE EXCEPTION 'Harvest must match crop context' USING ERRCODE='23514';
      END IF;
      IF NEW.plot_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM farm_plots WHERE plot_id=NEW.plot_id AND farm_id=NEW.farm_id) THEN
        RAISE EXCEPTION 'Harvest plot mismatch' USING ERRCODE='23514';
      END IF;
      IF NEW.farm_block_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM farm_blocks WHERE farm_block_id=NEW.farm_block_id AND farm_id=NEW.farm_id AND plot_id=NEW.plot_id) THEN
        RAISE EXCEPTION 'Harvest block mismatch' USING ERRCODE='23514';
      END IF;
      IF TG_OP='UPDATE' THEN
        IF ROW(NEW.farm_crop_id,NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.created_by,NEW.created_at,NEW.request_key,NEW.request_payload)
           IS DISTINCT FROM ROW(OLD.farm_crop_id,OLD.farm_id,OLD.plot_id,OLD.farm_block_id,OLD.created_by,OLD.created_at,OLD.request_key,OLD.request_payload) THEN
          RAISE EXCEPTION 'Harvest context and creation audit are immutable' USING ERRCODE='23514';
        END IF;
        SELECT coalesce(sum(quantity_sold),0),min(sold_on) INTO sold,first_sale FROM harvest_sales WHERE harvest_event_id=NEW.harvest_event_id;
        IF sold>NEW.quantity-coalesce(NEW.wastage_quantity,0) OR (sold>0 AND NEW.unit<>OLD.unit) OR NEW.harvested_on>first_sale THEN
          RAISE EXCEPTION 'Harvest correction conflicts with sales' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER harvest_event_guard BEFORE INSERT OR UPDATE ON harvest_events FOR EACH ROW EXECUTE FUNCTION harvest_event_guard();

    CREATE FUNCTION harvest_sale_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE event_row record; sold numeric;
    BEGIN
      SELECT * INTO event_row FROM harvest_events WHERE harvest_event_id=NEW.harvest_event_id FOR UPDATE;
      IF NOT FOUND OR NEW.unit<>event_row.unit OR NEW.sold_on<event_row.harvested_on THEN
        RAISE EXCEPTION 'Sale unit/date must match harvest' USING ERRCODE='23514';
      END IF;
      IF TG_OP='UPDATE' AND ROW(NEW.harvest_event_id,NEW.created_by,NEW.created_at,NEW.request_key,NEW.request_payload)
        IS DISTINCT FROM ROW(OLD.harvest_event_id,OLD.created_by,OLD.created_at,OLD.request_key,OLD.request_payload) THEN
        RAISE EXCEPTION 'Sale source and creation audit are immutable' USING ERRCODE='23514';
      END IF;
      SELECT coalesce(sum(quantity_sold),0) INTO sold FROM harvest_sales
        WHERE harvest_event_id=NEW.harvest_event_id AND harvest_sale_id<>NEW.harvest_sale_id;
      IF sold+NEW.quantity_sold>event_row.quantity-coalesce(event_row.wastage_quantity,0) THEN
        RAISE EXCEPTION 'Sales exceed sellable harvest quantity' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER harvest_sale_guard BEFORE INSERT OR UPDATE ON harvest_sales FOR EACH ROW EXECUTE FUNCTION harvest_sale_guard();
    CREATE FUNCTION harvest_cycle_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF ROW(NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.crop_id) IS DISTINCT FROM ROW(OLD.farm_id,OLD.plot_id,OLD.farm_block_id,OLD.crop_id)
        AND EXISTS(SELECT 1 FROM harvest_events WHERE farm_crop_id=OLD.farm_crop_id) THEN
        RAISE EXCEPTION 'Crop context with harvest history is immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER harvest_cycle_guard BEFORE UPDATE ON farm_crops FOR EACH ROW EXECUTE FUNCTION harvest_cycle_guard();
    """)


def downgrade():
    if op.get_bind().execute(text('SELECT EXISTS(SELECT 1 FROM harvest_events) OR EXISTS(SELECT 1 FROM harvest_sales)')).scalar():
        raise RuntimeError('Refusing to discard harvest or sales history.')
    op.execute('''DROP TRIGGER harvest_cycle_guard ON farm_crops;
      DROP TABLE harvest_sales; DROP TABLE harvest_events;
      DROP FUNCTION harvest_sale_guard(); DROP FUNCTION harvest_event_guard(); DROP FUNCTION harvest_cycle_guard();''')
