"""Persistent perennial identity with existing farm_crops as production periods."""
from alembic import op
from sqlalchemy import text

revision = 'b6e105f1d374'
down_revision = 'a5d094e0c263'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    CREATE TABLE perennial_plantings (
      perennial_planting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_farm_crop_id integer NOT NULL UNIQUE REFERENCES farm_crops ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      created_by integer NOT NULL REFERENCES users ON DELETE RESTRICT);
    ALTER TABLE farm_crops
      ADD COLUMN perennial_planting_id integer REFERENCES perennial_plantings ON DELETE RESTRICT,
      ADD COLUMN period_started_on date,
      ADD COLUMN period_request_key uuid,
      ADD COLUMN period_request_payload jsonb,
      ADD COLUMN completed_at timestamptz,
      ADD COLUMN completed_by integer REFERENCES users ON DELETE RESTRICT,
      ADD COLUMN completion_note text,
      ADD CONSTRAINT crop_completion_audit_pair CHECK((completed_at IS NULL)=(completed_by IS NULL)),
      ADD CONSTRAINT crop_completion_status CHECK(completed_at IS NULL OR status='harvested'),
      ADD CONSTRAINT crop_period_fields CHECK(perennial_planting_id IS NULL OR
        (period_started_on IS NOT NULL AND season IS NOT NULL AND length(trim(season))>0 AND planted_on IS NOT NULL AND period_started_on>=planted_on)),
      ADD CONSTRAINT crop_period_request_pair CHECK((period_request_key IS NULL)=(period_request_payload IS NULL));
    CREATE UNIQUE INDEX crop_one_open_season ON farm_crops(perennial_planting_id)
      WHERE perennial_planting_id IS NOT NULL AND status IN ('active','planned');
    CREATE UNIQUE INDEX crop_unique_season_name ON farm_crops(perennial_planting_id,lower(trim(season))) WHERE perennial_planting_id IS NOT NULL;
    CREATE UNIQUE INDEX crop_season_retry ON farm_crops(created_by,period_request_key) WHERE period_request_key IS NOT NULL;
    CREATE INDEX crop_planting_periods ON farm_crops(perennial_planting_id,period_started_on DESC) WHERE perennial_planting_id IS NOT NULL;
    CREATE FUNCTION perennial_identity_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE source_row record;
    BEGIN
      IF TG_TABLE_NAME='perennial_plantings' THEN
        IF TG_OP='UPDATE' THEN RAISE EXCEPTION 'Planting identity is immutable' USING ERRCODE='23514'; END IF;
        SELECT fc.* INTO source_row FROM farm_crops fc JOIN crops cr USING(crop_id)
          WHERE fc.farm_crop_id=NEW.source_farm_crop_id AND cr.lifecycle_type='perennial' AND fc.planted_on IS NOT NULL
            AND fc.status IN ('active','harvested') FOR UPDATE OF fc;
        IF NOT FOUND THEN RAISE EXCEPTION 'Choose an established perennial crop' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END IF;
      IF TG_OP='UPDATE' THEN
        IF OLD.perennial_planting_id IS NOT NULL AND ROW(NEW.perennial_planting_id,NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.crop_id,NEW.planted_on,
          NEW.crop_variety_id,NEW.planting_material_source_id,NEW.seed_or_material_lot,NEW.variety_text,NEW.planting_snapshot,NEW.season,NEW.period_started_on)
          IS DISTINCT FROM ROW(OLD.perennial_planting_id,OLD.farm_id,OLD.plot_id,OLD.farm_block_id,OLD.crop_id,OLD.planted_on,
          OLD.crop_variety_id,OLD.planting_material_source_id,OLD.seed_or_material_lot,OLD.variety_text,OLD.planting_snapshot,OLD.season,OLD.period_started_on) THEN
          RAISE EXCEPTION 'Established planting and season identity are immutable' USING ERRCODE='23514';
        END IF;
        IF OLD.completed_at IS NOT NULL AND ROW(NEW.completed_at,NEW.completed_by,NEW.completion_note) IS DISTINCT FROM ROW(OLD.completed_at,OLD.completed_by,OLD.completion_note) THEN
          RAISE EXCEPTION 'Completion audit is immutable' USING ERRCODE='23514';
        END IF;
        IF ROW(NEW.period_request_key,NEW.period_request_payload) IS DISTINCT FROM ROW(OLD.period_request_key,OLD.period_request_payload) THEN
          RAISE EXCEPTION 'Season retry identity is immutable' USING ERRCODE='23514';
        END IF;
      END IF;
      IF NEW.perennial_planting_id IS NOT NULL THEN
        SELECT fc.* INTO source_row FROM perennial_plantings p JOIN farm_crops fc ON fc.farm_crop_id=p.source_farm_crop_id
          WHERE p.perennial_planting_id=NEW.perennial_planting_id;
        IF NOT FOUND OR ROW(NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.crop_id,NEW.planted_on,NEW.crop_variety_id,NEW.planting_material_source_id,NEW.seed_or_material_lot,NEW.variety_text,NEW.planting_snapshot)
          IS DISTINCT FROM ROW(source_row.farm_id,source_row.plot_id,source_row.farm_block_id,source_row.crop_id,source_row.planted_on,source_row.crop_variety_id,source_row.planting_material_source_id,source_row.seed_or_material_lot,source_row.variety_text,source_row.planting_snapshot) THEN
          RAISE EXCEPTION 'Season must use its established planting context' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER perennial_identity_guard BEFORE INSERT OR UPDATE ON perennial_plantings FOR EACH ROW EXECUTE FUNCTION perennial_identity_guard();
    CREATE TRIGGER perennial_cycle_guard BEFORE INSERT OR UPDATE ON farm_crops FOR EACH ROW EXECUTE FUNCTION perennial_identity_guard();
    """)


def downgrade():
    if op.get_bind().execute(text('SELECT EXISTS(SELECT 1 FROM perennial_plantings) OR EXISTS(SELECT 1 FROM farm_crops WHERE completed_at IS NOT NULL)')).scalar():
        raise RuntimeError('Refusing to discard planting or completion history.')
    op.execute('''DROP TRIGGER perennial_cycle_guard ON farm_crops;
      ALTER TABLE farm_crops DROP COLUMN perennial_planting_id,DROP COLUMN period_started_on,
        DROP COLUMN period_request_key,DROP COLUMN period_request_payload,DROP COLUMN completed_at,DROP COLUMN completed_by,DROP COLUMN completion_note;
      DROP TABLE perennial_plantings; DROP FUNCTION perennial_identity_guard();''')
