"""Crop Management Slice 1: additive cycle audits and versioned task snapshots."""
from alembic import op
from sqlalchemy import text

revision = 'c901a7b2d310'
down_revision = '8b213a901def'
branch_labels = None
depends_on = None

TASK_TYPES = "'irrigation','fertilizer','pest_monitoring','disease_monitoring','weed_management','field_operation','harvest','inspection','general'"
SCHEDULE_TYPES = "'days_after_planting','days_before_harvest','crop_stage','condition','manual'"
AUDIT = """
created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
updated_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT
"""
SCHEDULE = f"""
task_type varchar(30) NOT NULL CHECK (task_type IN ({TASK_TYPES})),
schedule_type varchar(30) NOT NULL CHECK (schedule_type IN ({SCHEDULE_TYPES})),
offset_days integer,
crop_stage_key varchar(100),
condition_text text,
CHECK (
 (schedule_type IN ('days_after_planting','days_before_harvest') AND offset_days IS NOT NULL AND offset_days >= 0 AND crop_stage_key IS NULL AND condition_text IS NULL)
 OR (schedule_type='crop_stage' AND offset_days IS NULL AND crop_stage_key IS NOT NULL AND length(btrim(crop_stage_key)) > 0 AND condition_text IS NULL)
 OR (schedule_type='condition' AND offset_days IS NULL AND crop_stage_key IS NULL AND condition_text IS NOT NULL AND length(btrim(condition_text)) > 0)
 OR (schedule_type='manual' AND offset_days IS NULL AND crop_stage_key IS NULL AND condition_text IS NULL)
)
"""


def upgrade():
    op.execute("""ALTER TABLE farm_crops
      ADD COLUMN created_at timestamptz,
      ADD COLUMN updated_at timestamptz,
      ADD COLUMN created_by integer REFERENCES users(user_id) ON DELETE RESTRICT,
      ADD COLUMN updated_by integer REFERENCES users(user_id) ON DELETE RESTRICT""")
    op.execute(f"""CREATE TABLE sop_templates (
      sop_template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      crop_id integer NOT NULL REFERENCES crops(crop_id) ON DELETE RESTRICT,
      name varchar(150) NOT NULL CHECK (length(btrim(name)) BETWEEN 2 AND 150),
      description text, is_active boolean NOT NULL DEFAULT true, {AUDIT})""")
    op.execute(f"""CREATE TABLE sop_versions (
      sop_version_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      sop_template_id integer NOT NULL REFERENCES sop_templates(sop_template_id) ON DELETE RESTRICT,
      version_number integer NOT NULL CHECK (version_number > 0),
      status varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','retired')),
      version_notes text,
      published_at timestamptz, published_by integer REFERENCES users(user_id) ON DELETE RESTRICT,
      retired_at timestamptz, retired_by integer REFERENCES users(user_id) ON DELETE RESTRICT,
      {AUDIT}, UNIQUE(sop_template_id,version_number),
      CHECK ((status='draft' AND published_at IS NULL AND published_by IS NULL AND retired_at IS NULL AND retired_by IS NULL)
      OR (status='published' AND published_at IS NOT NULL AND published_by IS NOT NULL AND retired_at IS NULL AND retired_by IS NULL)
      OR (status='retired' AND published_at IS NOT NULL AND published_by IS NOT NULL AND retired_at IS NOT NULL AND retired_by IS NOT NULL)))""")
    op.execute(f"""CREATE TABLE sop_tasks (
      sop_task_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      sop_version_id integer NOT NULL REFERENCES sop_versions(sop_version_id) ON DELETE RESTRICT,
      sequence_no integer NOT NULL CHECK(sequence_no > 0),
      title varchar(200) NOT NULL CHECK(length(btrim(title)) > 0),
      instructions text NOT NULL CHECK(length(btrim(instructions)) > 0),
      {SCHEDULE}, {AUDIT}, UNIQUE(sop_version_id,sequence_no))""")
    op.execute("""CREATE TABLE crop_cycle_plans (
      plan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      farm_crop_id integer NOT NULL UNIQUE REFERENCES farm_crops(farm_crop_id) ON DELETE RESTRICT,
      sop_version_id integer NOT NULL REFERENCES sop_versions(sop_version_id) ON DELETE RESTRICT,
      anchor_date date NOT NULL,
      sop_template_name_snapshot varchar(150) NOT NULL CHECK(length(btrim(sop_template_name_snapshot)) > 0),
      sop_version_number_snapshot integer NOT NULL CHECK(sop_version_number_snapshot > 0),
      generated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      generated_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT)""")
    op.execute(f"""CREATE TABLE crop_tasks (
      crop_task_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      plan_id integer NOT NULL REFERENCES crop_cycle_plans(plan_id) ON DELETE RESTRICT,
      source_sop_task_id integer NOT NULL REFERENCES sop_tasks(sop_task_id) ON DELETE RESTRICT,
      sequence_no integer NOT NULL CHECK(sequence_no > 0),
      title varchar(200) NOT NULL CHECK(length(btrim(title)) > 0),
      instructions text NOT NULL CHECK(length(btrim(instructions)) > 0),
      {SCHEDULE}, due_date date,
      status varchar(20) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','in_progress','completed','partial','not_applicable','cancelled')),
      status_note text,
      completed_at timestamptz, completed_by integer REFERENCES users(user_id) ON DELETE RESTRICT,
      {AUDIT}, UNIQUE(plan_id,source_sop_task_id), UNIQUE(plan_id,sequence_no),
      CHECK(schedule_type NOT IN ('days_after_planting','days_before_harvest') OR due_date IS NOT NULL),
      CHECK((status='completed' AND completed_at IS NOT NULL AND completed_by IS NOT NULL)
        OR (status<>'completed' AND completed_at IS NULL AND completed_by IS NULL)),
      CHECK(status NOT IN ('partial','not_applicable','cancelled') OR (status_note IS NOT NULL AND length(btrim(status_note))>0)))""")
    for name, spec in [
        ('idx_sop_templates_crop_active','sop_templates(crop_id,is_active)'),
        ('idx_sop_versions_template_status','sop_versions(sop_template_id,status,version_number DESC)'),
        ('idx_crop_cycle_plans_version','crop_cycle_plans(sop_version_id)'),
        ('idx_crop_tasks_plan_status_due','crop_tasks(plan_id,status,due_date)'),
        ('idx_crop_tasks_open_due',"crop_tasks(due_date,plan_id) WHERE status IN ('pending','in_progress','partial')"),
        ('idx_farm_plots_farm','farm_plots(farm_id)'),
        ('idx_farm_crops_farm_status','farm_crops(farm_id,status)'),
        ('idx_farm_crops_plot','farm_crops(plot_id)'),
    ]:
        op.execute(f'CREATE INDEX {name} ON {spec}')
    op.execute("""
    CREATE FUNCTION cm_protect_template() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.crop_id IS DISTINCT FROM OLD.crop_id OR NEW.sop_template_id <> OLD.sop_template_id THEN
        RAISE EXCEPTION 'SOP template crop and identity are immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER cm_template_guard BEFORE UPDATE ON sop_templates
      FOR EACH ROW EXECUTE FUNCTION cm_protect_template();

    CREATE FUNCTION cm_protect_version() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='INSERT' THEN
        IF NEW.status <> 'draft' THEN RAISE EXCEPTION 'Versions must start as drafts' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END IF;
      IF TG_OP='DELETE' THEN
        IF OLD.status <> 'draft' THEN RAISE EXCEPTION 'Published SOP versions cannot be deleted' USING ERRCODE='23514'; END IF;
        RETURN OLD;
      END IF;
      IF NEW.sop_version_id <> OLD.sop_version_id OR NEW.sop_template_id <> OLD.sop_template_id OR NEW.version_number <> OLD.version_number THEN
        RAISE EXCEPTION 'Version identity is immutable' USING ERRCODE='23514';
      END IF;
      IF OLD.status <> 'draft' THEN
        IF NOT (OLD.status='published' AND NEW.status='retired' AND
          (to_jsonb(NEW) - ARRAY['status','retired_at','retired_by','updated_at','updated_by']) =
          (to_jsonb(OLD) - ARRAY['status','retired_at','retired_by','updated_at','updated_by'])) THEN
          RAISE EXCEPTION 'Published SOP content is immutable' USING ERRCODE='23514';
        END IF;
      ELSIF NEW.status <> 'draft' THEN
        IF NEW.status <> 'published' OR NOT EXISTS(SELECT 1 FROM sop_tasks WHERE sop_version_id=OLD.sop_version_id)
          OR EXISTS(SELECT 1 FROM sop_tasks WHERE sop_version_id=OLD.sop_version_id AND schedule_type<>'days_after_planting') THEN
          RAISE EXCEPTION 'Publication requires executable tasks' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER cm_version_guard BEFORE INSERT OR UPDATE OR DELETE ON sop_versions
      FOR EACH ROW EXECUTE FUNCTION cm_protect_version();

    CREATE FUNCTION cm_protect_sop_task() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE parent_status text; parent_id integer;
    BEGIN
      IF TG_OP='UPDATE' AND (NEW.sop_version_id<>OLD.sop_version_id OR NEW.sop_task_id<>OLD.sop_task_id) THEN
        RAISE EXCEPTION 'SOP task identity is immutable' USING ERRCODE='23514';
      END IF;
      IF TG_OP='DELETE' THEN parent_id := OLD.sop_version_id; ELSE parent_id := NEW.sop_version_id; END IF;
      SELECT status INTO parent_status FROM sop_versions WHERE sop_version_id=parent_id FOR UPDATE;
      IF parent_status IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION 'Only draft SOP tasks may change' USING ERRCODE='23514';
      END IF;
      IF TG_OP='DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER cm_sop_task_guard BEFORE INSERT OR UPDATE OR DELETE ON sop_tasks
      FOR EACH ROW EXECUTE FUNCTION cm_protect_sop_task();
    """)


def downgrade():
    connection = op.get_bind()
    for table in ('sop_templates','sop_versions','sop_tasks','crop_cycle_plans','crop_tasks'):
        if connection.execute(text(f'SELECT EXISTS(SELECT 1 FROM {table})')).scalar_one():
            raise RuntimeError('Refusing to delete populated Crop Management history.')
    if connection.execute(text('SELECT EXISTS(SELECT 1 FROM farm_crops WHERE created_at IS NOT NULL OR updated_at IS NOT NULL OR created_by IS NOT NULL OR updated_by IS NOT NULL)')).scalar_one():
        raise RuntimeError('Refusing to discard crop cycle audit history.')
    for table in ('crop_tasks','crop_cycle_plans','sop_tasks','sop_versions','sop_templates'):
        op.execute(f'DROP TABLE {table}')
    for function in ('cm_protect_sop_task','cm_protect_version','cm_protect_template'):
        op.execute(f'DROP FUNCTION {function}()')
    for index in ('idx_farm_plots_farm','idx_farm_crops_farm_status','idx_farm_crops_plot'):
        op.execute(f'DROP INDEX {index}')
    op.execute('ALTER TABLE farm_crops DROP COLUMN created_at, DROP COLUMN updated_at, DROP COLUMN created_by, DROP COLUMN updated_by')
