"""Assignment-scoped field work, preserving crop task execution and marketplace roles."""
from alembic import op
from sqlalchemy import text
revision = 'd2a041f9b620'
down_revision = 'c901a7b2d310'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE user_capabilities DROP CONSTRAINT user_capabilities_capability_check")
    op.execute("ALTER TABLE user_capabilities ADD CONSTRAINT user_capabilities_capability_check CHECK(capability IN ('farmer','provider','admin','field_officer'))")
    op.execute("""CREATE TABLE crop_officer_assignments (
      assignment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      field_officer_id integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
      farm_crop_id integer NOT NULL REFERENCES farm_crops(farm_crop_id) ON DELETE RESTRICT,
      assigned_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      assigned_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
      status varchar(20) NOT NULL DEFAULT 'active' CHECK(status IN ('active','completed','cancelled')),
      notes text,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT);
      CREATE UNIQUE INDEX uq_active_crop_officer ON crop_officer_assignments(field_officer_id,farm_crop_id) WHERE status='active';
      CREATE INDEX idx_assignment_crop ON crop_officer_assignments(farm_crop_id,assigned_at DESC);
      CREATE TABLE field_visits (
      visit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      assignment_id integer NOT NULL REFERENCES crop_officer_assignments(assignment_id) ON DELETE RESTRICT,
      planned_visit_date date NOT NULL,
      started_at timestamptz,
      completed_at timestamptz,
      status varchar(20) NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','in_progress','completed','cancelled')),
      visit_notes text,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      created_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
      CHECK ((status='planned' AND started_at IS NULL AND completed_at IS NULL)
        OR (status='in_progress' AND started_at IS NOT NULL AND completed_at IS NULL)
        OR (status='completed' AND started_at IS NOT NULL AND completed_at IS NOT NULL AND completed_at>=started_at)
        OR (status='cancelled' AND completed_at IS NULL)));
      CREATE INDEX idx_visits_assignment ON field_visits(assignment_id,planned_visit_date DESC);
      CREATE INDEX idx_visits_schedule ON field_visits(status,planned_visit_date);
      CREATE TABLE visit_tasks (
      visit_id integer NOT NULL REFERENCES field_visits(visit_id) ON DELETE RESTRICT,
      crop_task_id integer NOT NULL REFERENCES crop_tasks(crop_task_id) ON DELETE RESTRICT,
      verification_status varchar(30) NOT NULL DEFAULT 'unverified'
        CHECK(verification_status IN ('unverified','observed_completed','observed_partial','not_done','not_applicable','unable_to_verify')),
      officer_note text,
      verified_at timestamptz,
      verified_by integer REFERENCES users(user_id) ON DELETE RESTRICT,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY(visit_id,crop_task_id),
      CHECK((verification_status='unverified' AND verified_at IS NULL AND verified_by IS NULL)
        OR (verification_status<>'unverified' AND verified_at IS NOT NULL AND verified_by IS NOT NULL)),
      CHECK(verification_status IN ('unverified','observed_completed') OR (officer_note IS NOT NULL AND length(btrim(officer_note))>0)));
      CREATE INDEX idx_visit_tasks_crop_task ON visit_tasks(crop_task_id);
      CREATE TABLE field_observations (
      observation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visit_id integer NOT NULL REFERENCES field_visits(visit_id) ON DELETE RESTRICT,
      observation_type varchar(30) NOT NULL CHECK(observation_type IN ('general','crop_condition','pest','disease','weed','water','nutrient','damage')),
      severity varchar(10) NOT NULL CHECK(severity IN ('low','medium','high','critical')),
      title varchar(200) NOT NULL CHECK(length(btrim(title))>0),
      detailed_notes text NOT NULL CHECK(length(btrim(detailed_notes))>0),
      observed_at timestamptz NOT NULL,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      created_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
      updated_by integer NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT);
      CREATE INDEX idx_observations_visit ON field_observations(visit_id,observed_at DESC);
    """)
    op.execute("""CREATE FUNCTION fw_verify_task_cycle() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NOT EXISTS(SELECT 1 FROM field_visits v JOIN crop_officer_assignments a USING(assignment_id)
        JOIN crop_cycle_plans p ON p.farm_crop_id=a.farm_crop_id JOIN crop_tasks t USING(plan_id)
        WHERE v.visit_id=NEW.visit_id AND t.crop_task_id=NEW.crop_task_id) THEN
        RAISE EXCEPTION 'Visit task must belong to the assigned crop cycle' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER fw_task_cycle_guard BEFORE INSERT OR UPDATE ON visit_tasks FOR EACH ROW EXECUTE FUNCTION fw_verify_task_cycle();
    CREATE FUNCTION fw_keep_assignment_identity() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.field_officer_id<>OLD.field_officer_id OR NEW.farm_crop_id<>OLD.farm_crop_id OR NEW.assignment_id<>OLD.assignment_id THEN
        RAISE EXCEPTION 'Assignment identity is immutable; create another assignment' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER fw_assignment_guard BEFORE UPDATE ON crop_officer_assignments FOR EACH ROW EXECUTE FUNCTION fw_keep_assignment_identity();
    """)


def downgrade():
    c=op.get_bind()
    for table in ('crop_officer_assignments','field_visits','visit_tasks','field_observations'):
        if c.execute(text(f'SELECT EXISTS(SELECT 1 FROM {table})')).scalar_one():
            raise RuntimeError('Refusing to discard field-work history.')
    if c.execute(text("SELECT EXISTS(SELECT 1 FROM user_capabilities WHERE capability='field_officer')")).scalar_one():
        raise RuntimeError('Field officer capabilities must be reviewed before downgrade.')
    for table in ('field_observations','visit_tasks','field_visits','crop_officer_assignments'):op.execute(f'DROP TABLE {table}')
    op.execute('DROP FUNCTION fw_verify_task_cycle(); DROP FUNCTION fw_keep_assignment_identity();')
    op.execute('ALTER TABLE user_capabilities DROP CONSTRAINT user_capabilities_capability_check')
    op.execute("ALTER TABLE user_capabilities ADD CONSTRAINT user_capabilities_capability_check CHECK(capability IN ('farmer','provider','admin'))")
