"""Shared actual-work and expense ledger, with optional plot blocks."""
from alembic import op
from sqlalchemy import text

revision = 'e3b072c8a941'
down_revision = 'd2a041f9b620'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""CREATE TABLE farm_blocks (
      farm_block_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      farm_id integer NOT NULL REFERENCES farms ON DELETE RESTRICT,
      plot_id integer NOT NULL REFERENCES farm_plots ON DELETE RESTRICT,
      name varchar(150) NOT NULL CHECK(length(trim(name))>0), description text,
      area numeric(14,4) CHECK(area>0), area_unit varchar(20),
      status varchar(10) NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
      created_by integer NOT NULL REFERENCES users, updated_by integer NOT NULL REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      CHECK((area IS NULL AND area_unit IS NULL) OR (area IS NOT NULL AND area_unit IN ('acres','hectares','square_metres'))));
      CREATE INDEX idx_blocks_plot ON farm_blocks(farm_id,plot_id,status);
      ALTER TABLE farm_crops ADD COLUMN farm_block_id integer REFERENCES farm_blocks ON DELETE RESTRICT;
      CREATE INDEX idx_cycle_block ON farm_crops(farm_block_id);
      CREATE TABLE farm_activities (
      activity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      farm_id integer NOT NULL REFERENCES farms ON DELETE RESTRICT,
      plot_id integer REFERENCES farm_plots ON DELETE RESTRICT,
      farm_block_id integer REFERENCES farm_blocks ON DELETE RESTRICT,
      farm_crop_id integer REFERENCES farm_crops ON DELETE RESTRICT,
      crop_task_id integer REFERENCES crop_tasks ON DELETE RESTRICT,
      field_visit_id integer REFERENCES field_visits ON DELETE RESTRICT,
      service_booking_id integer REFERENCES bookings ON DELETE RESTRICT,
      activity_type varchar(30) NOT NULL CHECK(activity_type IN ('land_preparation','sowing_planting','irrigation','fertilizer','pesticide','weed_management','labour','machinery','pruning','inspection','harvest_support','transport','repair','other')),
      activity_date date NOT NULL, description text NOT NULL CHECK(length(trim(description))>0),
      quantity numeric(14,4) CHECK(quantity>0), unit varchar(50),
      performed_by_user_id integer REFERENCES users ON DELETE RESTRICT,
      source_type varchar(20) NOT NULL CHECK(source_type IN ('manual','crop_task','field_visit','service_booking')),
      notes text, request_key uuid NOT NULL, request_payload jsonb NOT NULL,
      created_by integer NOT NULL REFERENCES users, updated_by integer NOT NULL REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      UNIQUE(created_by,request_key),
      CHECK((quantity IS NULL AND unit IS NULL) OR (quantity IS NOT NULL AND length(trim(unit))>0)),
      CHECK((source_type='manual' AND crop_task_id IS NULL AND field_visit_id IS NULL AND service_booking_id IS NULL)
        OR (source_type='crop_task' AND crop_task_id IS NOT NULL AND field_visit_id IS NULL AND service_booking_id IS NULL)
        OR (source_type='field_visit' AND field_visit_id IS NOT NULL AND service_booking_id IS NULL)
        OR (source_type='service_booking' AND service_booking_id IS NOT NULL AND crop_task_id IS NULL AND field_visit_id IS NULL)));
      CREATE TABLE farm_expenses (
      expense_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      farm_id integer NOT NULL REFERENCES farms ON DELETE RESTRICT,
      plot_id integer REFERENCES farm_plots ON DELETE RESTRICT,
      farm_block_id integer REFERENCES farm_blocks ON DELETE RESTRICT,
      farm_crop_id integer REFERENCES farm_crops ON DELETE RESTRICT,
      activity_id integer REFERENCES farm_activities ON DELETE RESTRICT,
      expense_date date NOT NULL,
      category varchar(30) NOT NULL CHECK(category IN ('seed_planting_material','fertilizer','pesticide','labour','irrigation','diesel_fuel','machinery','repair','transport','harvesting','packing','electricity','miscellaneous')),
      amount numeric(14,2) NOT NULL CHECK(amount>0 AND amount<1000000000000),
      vendor_person varchar(200), payment_mode varchar(50), notes text,
      request_key uuid NOT NULL, request_payload jsonb NOT NULL,
      created_by integer NOT NULL REFERENCES users, updated_by integer NOT NULL REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      UNIQUE(created_by,request_key));
      CREATE INDEX idx_activities_farm_date ON farm_activities(farm_id,activity_date DESC,activity_id DESC);
      CREATE INDEX idx_expenses_farm_date ON farm_expenses(farm_id,expense_date DESC,expense_id DESC);
      CREATE INDEX idx_activity_task ON farm_activities(crop_task_id);
      CREATE INDEX idx_activity_visit ON farm_activities(field_visit_id);
      CREATE INDEX idx_activity_booking ON farm_activities(service_booking_id);
      CREATE INDEX idx_expense_activity ON farm_expenses(activity_id);
    """)
    for table in ('farm_activities','farm_expenses'):
        for scope in ('plot_id','farm_block_id','farm_crop_id'):
            op.execute(f'CREATE INDEX idx_{table}_{scope} ON {table}({scope})')
    op.execute("""CREATE FUNCTION ledger_context_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE r record;
    BEGIN
      IF NEW.plot_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM farm_plots WHERE plot_id=NEW.plot_id AND farm_id=NEW.farm_id) THEN
        RAISE EXCEPTION 'Plot/farm mismatch' USING ERRCODE='23514'; END IF;
      IF TG_TABLE_NAME='farm_blocks' THEN
        IF TG_OP='UPDATE' AND (NEW.farm_id,NEW.plot_id) IS DISTINCT FROM (OLD.farm_id,OLD.plot_id) THEN
          RAISE EXCEPTION 'Block context is immutable' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END IF;
      IF NEW.farm_block_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM farm_blocks WHERE farm_block_id=NEW.farm_block_id AND farm_id=NEW.farm_id AND plot_id=NEW.plot_id) THEN
        RAISE EXCEPTION 'Block context mismatch' USING ERRCODE='23514'; END IF;
      IF TG_TABLE_NAME='farm_crops' THEN
        IF TG_OP='UPDATE' AND (NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.crop_id) IS DISTINCT FROM (OLD.farm_id,OLD.plot_id,OLD.farm_block_id,OLD.crop_id)
          AND (EXISTS(SELECT 1 FROM farm_activities WHERE farm_crop_id=OLD.farm_crop_id) OR EXISTS(SELECT 1 FROM farm_expenses WHERE farm_crop_id=OLD.farm_crop_id)) THEN
          RAISE EXCEPTION 'Recorded crop context is immutable' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END IF;
      IF NEW.farm_crop_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM farm_crops WHERE farm_crop_id=NEW.farm_crop_id AND farm_id=NEW.farm_id AND plot_id IS NOT DISTINCT FROM NEW.plot_id AND farm_block_id IS NOT DISTINCT FROM NEW.farm_block_id) THEN
        RAISE EXCEPTION 'Crop context mismatch' USING ERRCODE='23514'; END IF;
      IF TG_OP='UPDATE' AND (NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.farm_crop_id,NEW.created_by,NEW.request_key,NEW.request_payload)
        IS DISTINCT FROM (OLD.farm_id,OLD.plot_id,OLD.farm_block_id,OLD.farm_crop_id,OLD.created_by,OLD.request_key,OLD.request_payload) THEN
        RAISE EXCEPTION 'Ledger context is immutable' USING ERRCODE='23514'; END IF;
      IF TG_TABLE_NAME='farm_activities' THEN
        IF NEW.crop_task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM crop_tasks t JOIN crop_cycle_plans p USING(plan_id) WHERE t.crop_task_id=NEW.crop_task_id AND p.farm_crop_id=NEW.farm_crop_id) THEN
          RAISE EXCEPTION 'Task/crop mismatch' USING ERRCODE='23514'; END IF;
        IF NEW.field_visit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM field_visits v JOIN crop_officer_assignments a USING(assignment_id) WHERE v.visit_id=NEW.field_visit_id AND a.farm_crop_id=NEW.farm_crop_id) THEN
          RAISE EXCEPTION 'Visit/crop mismatch' USING ERRCODE='23514'; END IF;
        IF NEW.service_booking_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM bookings b JOIN farms f ON f.farm_id=b.farm_id WHERE b.booking_id=NEW.service_booking_id AND b.farm_id=NEW.farm_id AND b.farmer_id=f.farmer_id) THEN
          RAISE EXCEPTION 'Booking/farm mismatch' USING ERRCODE='23514'; END IF;
        IF TG_OP='UPDATE' AND (NEW.crop_task_id,NEW.field_visit_id,NEW.service_booking_id,NEW.source_type) IS DISTINCT FROM (OLD.crop_task_id,OLD.field_visit_id,OLD.service_booking_id,OLD.source_type) THEN
          RAISE EXCEPTION 'Activity source is immutable' USING ERRCODE='23514'; END IF;
      ELSE
        IF NEW.activity_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM farm_activities a WHERE a.activity_id=NEW.activity_id AND (a.farm_id,a.plot_id,a.farm_block_id,a.farm_crop_id) IS NOT DISTINCT FROM (NEW.farm_id,NEW.plot_id,NEW.farm_block_id,NEW.farm_crop_id)) THEN
          RAISE EXCEPTION 'Expense/activity mismatch' USING ERRCODE='23514'; END IF;
        IF TG_OP='UPDATE' AND NEW.activity_id IS DISTINCT FROM OLD.activity_id THEN
          RAISE EXCEPTION 'Expense link is immutable' USING ERRCODE='23514'; END IF;
      END IF;
      RETURN NEW;
    END $$;
    """)
    for table in ('farm_blocks','farm_crops','farm_activities','farm_expenses'):
        op.execute(f'CREATE TRIGGER ledger_context BEFORE INSERT OR UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION ledger_context_guard()')


def downgrade():
    c = op.get_bind()
    if any(c.execute(text(f'SELECT EXISTS(SELECT 1 FROM {t})')).scalar_one() for t in ('farm_expenses','farm_activities','farm_blocks')):
        raise RuntimeError('Refusing to discard farm work or financial history.')
    for table in ('farm_blocks','farm_crops','farm_activities','farm_expenses'):
        op.execute(f'DROP TRIGGER ledger_context ON {table}')
    op.execute('DROP FUNCTION ledger_context_guard(); DROP TABLE farm_expenses; DROP TABLE farm_activities; ALTER TABLE farm_crops DROP COLUMN farm_block_id; DROP TABLE farm_blocks;')
