"""Neutral shared accounts and reviewed field officer applications."""
from alembic import op
from sqlalchemy import text

revision = 'e9b438c4a607'
down_revision = 'd8a327b3f596'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""ALTER TABLE users DROP CONSTRAINT users_user_role_check;
      ALTER TABLE users ADD CONSTRAINT users_user_role_check CHECK(user_role IN ('farmer','supplier','admin','member')),
        ADD COLUMN signup_intent varchar(20) CHECK(signup_intent IN ('farmer','provider','field_officer','landowner'));
      CREATE TABLE field_officer_applications (
        application_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id integer NOT NULL UNIQUE REFERENCES users ON DELETE RESTRICT,
        status varchar(15) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
        qualification varchar(300), experience_years numeric(4,1) CHECK(experience_years>=0 AND experience_years<=80),
        crops_or_domains_known varchar(1000), operating_area_text varchar(500), languages_known varchar(300), notes varchar(2000),
        created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
        reviewed_at timestamptz, reviewed_by integer REFERENCES users ON DELETE RESTRICT, rejection_reason varchar(2000),
        CHECK(reviewed_by IS NULL OR reviewed_by<>user_id),
        CHECK((status='pending' AND reviewed_at IS NULL AND reviewed_by IS NULL AND rejection_reason IS NULL)
          OR (status='approved' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND rejection_reason IS NULL)
          OR (status='rejected' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND length(trim(rejection_reason))>0 AND rejection_reason IS NOT NULL)));
      CREATE INDEX officer_application_queue ON field_officer_applications(status,created_at,application_id);
      CREATE FUNCTION officer_application_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF TG_OP='INSERT' THEN
          IF NEW.status<>'pending' THEN RAISE EXCEPTION 'Applications must start pending' USING ERRCODE='23514'; END IF;
        ELSE
          IF OLD.status<>'pending' OR NEW.status NOT IN ('approved','rejected') OR
            (to_jsonb(NEW)-ARRAY['status','updated_at','reviewed_at','reviewed_by','rejection_reason']) IS DISTINCT FROM
            (to_jsonb(OLD)-ARRAY['status','updated_at','reviewed_at','reviewed_by','rejection_reason']) THEN
            RAISE EXCEPTION 'Submitted application content and completed review are immutable' USING ERRCODE='23514'; END IF;
          IF NEW.reviewed_by=NEW.user_id OR NOT EXISTS(SELECT 1 FROM users u WHERE u.user_id=NEW.reviewed_by AND
            (u.user_role='admin' OR EXISTS(SELECT 1 FROM user_capabilities uc WHERE uc.user_id=u.user_id AND uc.capability='admin'))) THEN
            RAISE EXCEPTION 'Independent admin review is required' USING ERRCODE='23514'; END IF;
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER officer_application_guard BEFORE INSERT OR UPDATE ON field_officer_applications
        FOR EACH ROW EXECUTE FUNCTION officer_application_guard();
      CREATE FUNCTION officer_application_approval() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF NEW.status='approved' THEN
          INSERT INTO user_capabilities(user_id,capability) VALUES(NEW.user_id,'field_officer') ON CONFLICT DO NOTHING;
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER officer_application_approval AFTER UPDATE ON field_officer_applications
        FOR EACH ROW EXECUTE FUNCTION officer_application_approval();
      CREATE FUNCTION officer_applicant_access_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF NEW.capability='field_officer' AND EXISTS(SELECT 1 FROM field_officer_applications WHERE user_id=NEW.user_id AND status<>'approved') THEN
          RAISE EXCEPTION 'Review the officer application before granting access' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER officer_applicant_access_guard BEFORE INSERT OR UPDATE ON user_capabilities
        FOR EACH ROW EXECUTE FUNCTION officer_applicant_access_guard();
    """)


def downgrade():
    c=op.get_bind()
    if c.execute(text("SELECT EXISTS(SELECT 1 FROM field_officer_applications) OR EXISTS(SELECT 1 FROM users WHERE signup_intent IS NOT NULL OR user_role='member')")).scalar_one():
        raise RuntimeError('Refusing to discard signup or application history.')
    op.execute("""DROP TRIGGER officer_applicant_access_guard ON user_capabilities; DROP FUNCTION officer_applicant_access_guard();
      DROP TABLE field_officer_applications; DROP FUNCTION officer_application_guard(); DROP FUNCTION officer_application_approval();
      ALTER TABLE users DROP COLUMN signup_intent, DROP CONSTRAINT users_user_role_check;
      ALTER TABLE users ADD CONSTRAINT users_user_role_check CHECK(user_role IN ('farmer','supplier','admin'));""")
