"""Optional planting identity and factual input usage, preserving historical labels."""
from alembic import op
from sqlalchemy import text

revision = 'f4c083d9b152'
down_revision = 'e3b072c8a941'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""ALTER TABLE crops
      ADD COLUMN crop_group varchar(12) CHECK(crop_group IN ('orchard','seasonal','vegetable')),
      ADD COLUMN lifecycle_type varchar(12) CHECK(lifecycle_type IN ('seasonal','perennial')),
      ADD COLUMN harvest_pattern varchar(12) CHECK(harvest_pattern IN ('single','multiple','recurring'));
      CREATE TABLE planting_material_sources (
      planting_material_source_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_name varchar(200) NOT NULL CHECK(length(trim(source_name))>0), brand_name varchar(200),
      source_type varchar(30) NOT NULL CHECK(source_type IN ('seed_company','nursery','tissue_culture_supplier','farmer_saved','local_supplier','other')),
      notes text, status varchar(10) NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
      created_by integer REFERENCES users, updated_by integer REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp());
      CREATE TABLE crop_varieties (
      crop_variety_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      crop_id integer NOT NULL REFERENCES crops ON DELETE RESTRICT,
      variety_name varchar(200) NOT NULL CHECK(length(trim(variety_name))>0),
      variety_type varchar(20) CHECK(variety_type IN ('hybrid','open_pollinated','cultivar','clone','local','other')),
      default_planting_material_source_id integer REFERENCES planting_material_sources ON DELETE RESTRICT,
      duration_min_days integer CHECK(duration_min_days BETWEEN 1 AND 36500),
      duration_max_days integer CHECK(duration_max_days BETWEEN 1 AND 36500),
      days_to_first_harvest_min integer CHECK(days_to_first_harvest_min BETWEEN 1 AND 36500),
      days_to_first_harvest_max integer CHECK(days_to_first_harvest_max BETWEEN 1 AND 36500),
      notes text, status varchar(10) NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
      created_by integer REFERENCES users, updated_by integer REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      UNIQUE(crop_variety_id,crop_id),
      CHECK(duration_min_days<=duration_max_days), CHECK(days_to_first_harvest_min<=days_to_first_harvest_max));
      CREATE UNIQUE INDEX uq_active_variety_name ON crop_varieties(crop_id,lower(regexp_replace(trim(variety_name),'[[:space:]]+',' ','g'))) WHERE status='active';
      CREATE INDEX idx_varieties_crop ON crop_varieties(crop_id,status);
      CREATE INDEX idx_sources_status ON planting_material_sources(status,source_name);
      ALTER TABLE farm_crops
      ADD COLUMN crop_variety_id integer,
      ADD COLUMN planting_material_source_id integer REFERENCES planting_material_sources ON DELETE RESTRICT,
      ADD COLUMN seed_or_material_lot varchar(150),
      ADD COLUMN variety_text varchar(200),
      ADD COLUMN planting_snapshot jsonb CHECK(planting_snapshot IS NULL OR jsonb_typeof(planting_snapshot)='object'),
      ADD CONSTRAINT fk_planting_variety_crop FOREIGN KEY(crop_variety_id,crop_id) REFERENCES crop_varieties(crop_variety_id,crop_id) ON DELETE RESTRICT,
      ADD CONSTRAINT ck_planting_variety_choice CHECK(crop_variety_id IS NULL OR variety_text IS NULL);
      CREATE INDEX idx_planting_variety ON farm_crops(crop_variety_id);
      CREATE INDEX idx_planting_source ON farm_crops(planting_material_source_id);
      CREATE TABLE farm_input_products (
      farm_input_product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      input_type varchar(25) NOT NULL CHECK(input_type IN ('fertilizer','pesticide','fungicide','herbicide','bio_input','growth_regulator','soil_amendment','micronutrient','other')),
      product_name varchar(200) NOT NULL CHECK(length(trim(product_name))>0),
      brand_name varchar(200), manufacturer_name varchar(200), active_ingredient text,
      formulation varchar(200), nutrient_composition jsonb CHECK(nutrient_composition IS NULL OR jsonb_typeof(nutrient_composition)='object'),
      default_unit varchar(10) CHECK(default_unit IN ('kg','g','L','ml','tonne','unit')),
      notes text, status varchar(10) NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),
      created_by integer REFERENCES users, updated_by integer REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp());
      CREATE INDEX idx_input_type_status ON farm_input_products(input_type,status);
      CREATE TABLE farm_activity_inputs (
      farm_activity_input_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      activity_id integer NOT NULL REFERENCES farm_activities ON DELETE RESTRICT,
      farm_input_product_id integer REFERENCES farm_input_products ON DELETE RESTRICT,
      product_snapshot jsonb NOT NULL CHECK(jsonb_typeof(product_snapshot)='object' AND length(trim(product_snapshot->>'product_name'))>0),
      is_unlisted boolean NOT NULL,
      quantity numeric(14,4) NOT NULL CHECK(quantity>0 AND quantity<10000000000),
      unit varchar(10) NOT NULL CHECK(unit IN ('kg','g','L','ml','tonne','unit')),
      application_method varchar(200), target_reason text, notes text,
      created_by integer NOT NULL REFERENCES users, updated_by integer NOT NULL REFERENCES users,
      created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      request_key uuid NOT NULL, request_payload jsonb NOT NULL,
      UNIQUE(activity_id,request_key), CHECK(is_unlisted=(farm_input_product_id IS NULL)));
      CREATE INDEX idx_usage_product ON farm_activity_inputs(farm_input_product_id);
      CREATE FUNCTION keep_input_identity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF (NEW.activity_id,NEW.farm_input_product_id,NEW.product_snapshot,NEW.is_unlisted,NEW.created_by,NEW.created_at,NEW.request_key,NEW.request_payload)
          IS DISTINCT FROM (OLD.activity_id,OLD.farm_input_product_id,OLD.product_snapshot,OLD.is_unlisted,OLD.created_by,OLD.created_at,OLD.request_key,OLD.request_payload) THEN
          RAISE EXCEPTION 'Input identity and snapshot are immutable' USING ERRCODE='23514'; END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER input_identity BEFORE UPDATE ON farm_activity_inputs FOR EACH ROW EXECUTE FUNCTION keep_input_identity();
    """)


def downgrade():
    c=op.get_bind()
    tables=('farm_activity_inputs','farm_input_products','crop_varieties','planting_material_sources')
    if any(c.execute(text(f'SELECT EXISTS(SELECT 1 FROM {table})')).scalar_one() for table in tables):
        raise RuntimeError('Refusing to discard catalogue or input history.')
    if c.execute(text('SELECT EXISTS(SELECT 1 FROM farm_crops WHERE planting_snapshot IS NOT NULL OR variety_text IS NOT NULL OR seed_or_material_lot IS NOT NULL)')).scalar_one():
        raise RuntimeError('Refusing to discard planting history.')
    if c.execute(text('SELECT EXISTS(SELECT 1 FROM crops WHERE crop_group IS NOT NULL OR lifecycle_type IS NOT NULL OR harvest_pattern IS NOT NULL)')).scalar_one():
        raise RuntimeError('Refusing to discard crop metadata.')
    op.execute('DROP TABLE farm_activity_inputs; DROP FUNCTION keep_input_identity(); DROP TABLE farm_input_products; ALTER TABLE farm_crops DROP COLUMN crop_variety_id,DROP COLUMN planting_material_source_id,DROP COLUMN seed_or_material_lot,DROP COLUMN variety_text,DROP COLUMN planting_snapshot; DROP TABLE crop_varieties; DROP TABLE planting_material_sources; ALTER TABLE crops DROP COLUMN crop_group,DROP COLUMN lifecycle_type,DROP COLUMN harvest_pattern;')
